apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hulj7skbp-go 
  janus-idp.io/tekton: hulj7skbp-go
  backstage.io/kubernetes-id: hulj7skbp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hulj7skbp-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml